### PR TITLE
Updated to Swift 3.0

### PR DESCRIPTION
**Pull request by pushchris**
I went through and updated the pod & tests to function with Swift 3.0

### CODE REVIEW

**Comment by danydev** [comment]
Thanks! it was on my todo list, great work!
Can you take care of fixing travis build as well? you probably just need to change `osx_image` in `.travis.yml` to `xcode8`

**Comment by pushchris** [comment]
Something seems to be screwy with Travis right now. Will look into it a bit later when I have some more time to mess around with it.

**Comment by danydev** [comment]
Sure, thanks!
At a first sight, it looks like the last xctool changed the way you run it, so we either update the `script` command inside `.travis.yml` to something like `xctool -workspace RateLimit.xcworkspace -scheme RateLimit\ Tests -sdk iphonesimulator9.3 run-tests`
or we try to not upgrade xctool at all (since I upgraded xctool to workaround a bug that was only on Xcode 7.3)

**Comment by pushchris** [comment]
Alright, so there are a bunch of issues in play here. It looks like xctool has been abandoned by Facebook and has quite a few issues with Xcode 8 [https://github.com/facebook/xctool/issues/704](url). I switched over to `xcodebuild`, however, that as well seems to be having some issues [https://github.com/travis-ci/travis-ci/issues/6422](url). Still looking into a solution at this point.

**Comment by danydev** [comment]
great! merged

**Pull request merged**
